# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: VideoLAN.VLC
PackageVersion: 3.0.14
MinimumOSVersion: 10.0.0.0
FileExtensions:
- 264
- 3ga
- 3gp
- aac
- avi
- cda
- dash
- dvr
- flac
- ifo
- m2t
- m2ts
- m3u8
- m4v
- mkv
- mov
- mp3
- mp4
- mpg
- mts
- ogg
- ogv
- opus
- pls
- rec
- rmvb
- snd
- sub
- ts
- vob
- webm
- wma
- wmv
- zab
Commands:
- vlc
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://download.videolan.org/vlc/3.0.14/win64/vlc-3.0.14-win64.msi
  InstallerSha256: 2244fdba295ee082147413efbc2fc8621ed448bfc9a7d32b312836a36c328ac0
  #ProductCode: "{496FB7DC-40C7-41A7-8373-A0E2F001CC37}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.videolan.org/vlc/3.0.14/win32/vlc-3.0.14-win32.msi
  InstallerSha256: b4e876c059946462c141765a9dc1c8c2435462f81a3f0f4bb1e76e2997d49ebf
  #ProductCode: "{A3263831-98B6-4DC7-8D3F-BDC2365DE42A}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
